version: '3.8'
services:
  movies:
    image: varunaws999/movies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  trains:
    image: varunaws999/trains:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  recharge:
    image: varunaws999/recharge:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  dth:
    image: varunaws999/dth:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
